name: shared_prefs_typed_annotations
description: Annotations for generating type-safe SharedPreferences code (shared_prefs_typed)
repository: https://github.com/PhilippHGerber/shared_prefs_typed.git
version: 0.5.1

environment:
  sdk: ^3.7.0

resolution: workspace

dev_dependencies:
  test: ^1.25.0
  very_good_analysis: ^9.0.0
