name: shared_prefs_typed_annotations
description: Annotations for generating type-safe SharedPreferences code (shared_prefs_typed)
repository: https://github.com/PhilippHGerber/shared_prefs_typed.git
version: 0.5.2

environment:
  sdk: ^3.9.0

resolution: workspace

dev_dependencies:
  test: ^1.29.0
  very_good_analysis: ^10.2.0
