/// This integration test suite validates the runtime behavior of the code
/// generated by the `shared_prefs_typed` package.
///
/// It ensures that the generated `AppPreferencesImpl` service class correctly interacts
/// with the underlying `shared_preferences` plugin's modern asynchronous APIs
/// for all supported data types and scenarios (getting, setting, removing, etc.).
library;

// Import the generated code.
import 'package:basic_example/app_preferences.g.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:shared_preferences_platform_interface/in_memory_shared_preferences_async.dart';
import 'package:shared_preferences_platform_interface/shared_preferences_async_platform_interface.dart';
import 'package:shared_preferences_platform_interface/types.dart';

void main() {
  /// This `setUpAll` block runs once before any tests in this suite.
  /// It's the ideal place for one-time setup.
  setUpAll(() {
    // Ensures that the Flutter test framework is initialized.
    TestWidgetsFlutterBinding.ensureInitialized();

    // CRITICAL SETUP FOR MODERN `shared_preferences` (v2.3.0+):
    // In a test environment, the native platform implementation (like Android's
    // DataStore or iOS's NSUserDefaults) is not available. We must manually
    // provide a "platform implementation".
    // `InMemorySharedPreferencesAsync` is a pure Dart, in-memory store
    // provided by the `shared_preferences_platform_interface` package,
    // which is perfect for fast and reliable tests.
    SharedPreferencesAsyncPlatform.instance = InMemorySharedPreferencesAsync.empty();
  });

  group('AppPreferences Generated Code Tests', () {
    // A late-initialized variable to hold the singleton instance of our
    // generated preferences service.
    late AppPreferencesImpl prefs;

    /// This `setUp` block runs before each individual test within this group.
    /// This is used to ensure that each test starts from a clean, isolated state.
    setUp(() async {
      // 1. Get the singleton instance of our in-memory store.
      final store = SharedPreferencesAsyncPlatform.instance;

      // 2. Clear all data from the in-memory store to prevent state leakage
      //    between tests.
      await store?.clear(
        const ClearPreferencesParameters(filter: PreferencesFilters()),
        const SharedPreferencesOptions(),
      );

      // 3. Reset the singleton so init() creates a fresh SharedPreferencesWithCache
      //    that reads from the now-empty in-memory store (no stale cache).
      AppPreferencesImpl.resetInstance();

      // 4. Initialize our generated `AppPreferencesImpl` service. It will automatically
      //    use the `InMemorySharedPreferencesAsync` instance we set up in `setUpAll`.
      await AppPreferencesImpl.init();
      prefs = AppPreferencesImpl.instance;
    });

    group('for int (counter)', () {
      test('returns default value initially', () {
        expect(prefs.counter, 0);
        expect(prefs.containsCounter(), isFalse);
      });

      test('sets and gets a value correctly', () async {
        await prefs.setCounter(42);
        expect(prefs.counter, 42);
        expect(prefs.containsCounter(), isTrue);
      });

      test('removes a value, reverting to default', () async {
        await prefs.setCounter(42);
        expect(prefs.counter, 42); // Verify it was set.

        await prefs.removeCounter();
        expect(prefs.counter, 0); // Should be back to default.
        expect(prefs.containsCounter(), isFalse);
      });
    });

    group('for double (pi)', () {
      test('returns default value initially', () {
        expect(prefs.pi, 3.14);
        expect(prefs.containsPi(), isFalse);
      });

      test('sets and gets a value correctly', () async {
        await prefs.setPi(2.718);
        expect(prefs.pi, 2.718);
        expect(prefs.containsPi(), isTrue);
      });

      test('removes a value, reverting to default', () async {
        await prefs.setPi(2.718);
        await prefs.removePi();
        expect(prefs.pi, 3.14);
        expect(prefs.containsPi(), isFalse);
      });
    });

    group('for bool (isWelcomeScreenDone)', () {
      test('returns default value initially', () {
        expect(prefs.isWelcomeScreenDone, isFalse);
        expect(prefs.containsIsWelcomeScreenDone(), isFalse);
      });

      test('sets and gets a value correctly', () async {
        await prefs.setIsWelcomeScreenDone(true);
        expect(prefs.isWelcomeScreenDone, isTrue);
        expect(prefs.containsIsWelcomeScreenDone(), isTrue);
      });

      test('removes a value, reverting to default', () async {
        await prefs.setIsWelcomeScreenDone(true);
        await prefs.removeIsWelcomeScreenDone();
        expect(prefs.isWelcomeScreenDone, isFalse);
        expect(prefs.containsIsWelcomeScreenDone(), isFalse);
      });
    });

    group('for String (greeting)', () {
      test('returns default value initially', () {
        expect(prefs.greeting, 'Hello');
        expect(prefs.containsGreeting(), isFalse);
      });

      test('sets and gets a value correctly', () async {
        await prefs.setGreeting('World');
        expect(prefs.greeting, 'World');
        expect(prefs.containsGreeting(), isTrue);
      });

      test('removes a value, reverting to default', () async {
        await prefs.setGreeting('World');
        await prefs.removeGreeting();
        expect(prefs.greeting, 'Hello');
        expect(prefs.containsGreeting(), isFalse);
      });
    });

    group('for List<String> (tagList)', () {
      test('returns default value initially', () {
        expect(prefs.tagList, ['default']);
        expect(prefs.containsTagList(), isFalse);
      });

      test('sets and gets a value correctly', () async {
        await prefs.setTagList(['flutter', 'dart']);
        expect(prefs.tagList, ['flutter', 'dart']);
        expect(prefs.containsTagList(), isTrue);
      });

      test('removes a value, reverting to default', () async {
        await prefs.setTagList(['flutter', 'dart']);
        await prefs.removeTagList();
        expect(prefs.tagList, ['default']);
        expect(prefs.containsTagList(), isFalse);
      });
    });

    group('for List<int> (recentItemIds)', () {
      test('returns default value (empty list) initially', () {
        expect(prefs.recentItemIds, isEmpty);
        expect(prefs.containsRecentItemIds(), isFalse);
      });

      test('sets and gets a value correctly', () async {
        await prefs.setRecentItemIds([1, 2, 3]);
        expect(prefs.recentItemIds, [1, 2, 3]);
        expect(prefs.containsRecentItemIds(), isTrue);
      });

      test('removes a value, reverting to default', () async {
        await prefs.setRecentItemIds([10, 20]);
        await prefs.removeRecentItemIds();
        expect(prefs.recentItemIds, isEmpty);
        expect(prefs.containsRecentItemIds(), isFalse);
      });

      test('round-trips negative values correctly', () async {
        await prefs.setRecentItemIds([-1, 0, 42]);
        expect(prefs.recentItemIds, [-1, 0, 42]);
      });
    });

    group('for List<double> (priceHistory)', () {
      test('returns default value initially', () {
        expect(prefs.priceHistory, [9.99, 14.99, 19.99]);
        expect(prefs.containsPriceHistory(), isFalse);
      });

      test('sets and gets a value correctly', () async {
        await prefs.setPriceHistory([1.5, 2.5, 3.5]);
        expect(prefs.priceHistory, [1.5, 2.5, 3.5]);
        expect(prefs.containsPriceHistory(), isTrue);
      });

      test('removes a value, reverting to default', () async {
        await prefs.setPriceHistory([0.99]);
        await prefs.removePriceHistory();
        expect(prefs.priceHistory, [9.99, 14.99, 19.99]);
        expect(prefs.containsPriceHistory(), isFalse);
      });
    });

    group('for nullable String (sessionId)', () {
      test('returns default value (null) initially', () {
        expect(prefs.sessionId, isNull);
        expect(prefs.containsSessionId(), isFalse);
      });

      test('sets and gets a value correctly', () async {
        await prefs.setSessionId('abc-123');
        expect(prefs.sessionId, 'abc-123');
        expect(prefs.containsSessionId(), isTrue);
      });

      test('setting to null removes the value', () async {
        await prefs.setSessionId('abc-123');
        expect(prefs.containsSessionId(), isTrue); // Verify it was set.

        await prefs.setSessionId(null); // Set to null.
        expect(prefs.sessionId, isNull); // Should be back to default (null).
        expect(prefs.containsSessionId(), isFalse);
      });
    });

    group('for nullable int with non-null default (nullableCounterWithDefault)', () {
      test('returns default value (100) initially', () {
        expect(prefs.nullableCounterWithDefault, 100);
        expect(prefs.containsNullableCounterWithDefault(), isFalse);
      });

      test('sets and gets a value correctly', () async {
        await prefs.setNullableCounterWithDefault(999);
        expect(prefs.nullableCounterWithDefault, 999);
        expect(prefs.containsNullableCounterWithDefault(), isTrue);
      });

      test('setting to null removes the value, reverting to default', () async {
        await prefs.setNullableCounterWithDefault(999);
        expect(prefs.containsNullableCounterWithDefault(), isTrue);

        await prefs.setNullableCounterWithDefault(null);
        expect(prefs.nullableCounterWithDefault, 100); // Should be back to default.
        expect(prefs.containsNullableCounterWithDefault(), isFalse);
      });

      test('explicit remove reverts to default', () async {
        await prefs.setNullableCounterWithDefault(999);
        await prefs.removeNullableCounterWithDefault();
        expect(prefs.nullableCounterWithDefault, 100);
        expect(prefs.containsNullableCounterWithDefault(), isFalse);
      });
    });

    group('clearAll()', () {
      test('reverts all fields to their defaults', () async {
        await prefs.setCounter(42);
        await prefs.setPi(2.718);
        await prefs.setIsWelcomeScreenDone(true);
        await prefs.setGreeting('Hi');
        await prefs.setTagList(['a', 'b']);
        await prefs.setSessionId('session-1');

        await prefs.clearAll();

        expect(prefs.counter, 0);
        expect(prefs.pi, 3.14);
        expect(prefs.isWelcomeScreenDone, isFalse);
        expect(prefs.greeting, 'Hello');
        expect(prefs.tagList, ['default']);
        expect(prefs.sessionId, isNull);
        expect(prefs.containsCounter(), isFalse);
        expect(prefs.containsGreeting(), isFalse);
      });
    });
  });

  group('type migration resilience', () {
    // Writes a value with an incompatible type directly to the platform store,
    // then initialises the cache on top of it. The generated getter's try/catch
    // guard must catch the resulting TypeError and return the field's default.
    setUp(() async {
      await SharedPreferencesAsyncPlatform.instance?.clear(
        const ClearPreferencesParameters(filter: PreferencesFilters()),
        const SharedPreferencesOptions(),
      );
      AppPreferencesImpl.resetInstance();
      AppPreferencesImpl.onReadError = null;
    });

    test('int field returns default when stored as String', () async {
      await SharedPreferencesAsyncPlatform.instance!
          .setString('counter', 'not-an-int', const SharedPreferencesOptions());
      await AppPreferencesImpl.init();
      expect(AppPreferencesImpl.instance.counter, 0);
    });

    test('double field returns default when stored as String', () async {
      await SharedPreferencesAsyncPlatform.instance!
          .setString('pi', 'not-a-double', const SharedPreferencesOptions());
      await AppPreferencesImpl.init();
      expect(AppPreferencesImpl.instance.pi, 3.14);
    });

    test('bool field returns default when stored as String', () async {
      await SharedPreferencesAsyncPlatform.instance!
          .setString('isWelcomeScreenDone', 'bad', const SharedPreferencesOptions());
      await AppPreferencesImpl.init();
      expect(AppPreferencesImpl.instance.isWelcomeScreenDone, isFalse);
    });

    test('String field returns default when stored as int', () async {
      await SharedPreferencesAsyncPlatform.instance!
          .setInt('greeting', 42, const SharedPreferencesOptions());
      await AppPreferencesImpl.init();
      expect(AppPreferencesImpl.instance.greeting, 'Hello');
    });

    test('DateTime ISO 8601 field returns default on malformed string', () async {
      await SharedPreferencesAsyncPlatform.instance!
          .setString('lastSyncDate', 'not-a-date', const SharedPreferencesOptions());
      await AppPreferencesImpl.init();
      expect(AppPreferencesImpl.instance.lastSyncDate, isNull);
    });

    test('DateTime millis field returns default when stored as String', () async {
      await SharedPreferencesAsyncPlatform.instance!
          .setString('lastLoginDate', 'bad', const SharedPreferencesOptions());
      await AppPreferencesImpl.init();
      expect(AppPreferencesImpl.instance.lastLoginDate, isNull);
    });

    test('onReadError callback is invoked on type mismatch', () async {
      await SharedPreferencesAsyncPlatform.instance!
          .setString('counter', 'bad', const SharedPreferencesOptions());
      await AppPreferencesImpl.init();

      String? capturedKey;
      Object? capturedError;
      AppPreferencesImpl.onReadError = (key, error) {
        capturedKey = key;
        capturedError = error;
      };
      addTearDown(() => AppPreferencesImpl.onReadError = null);

      AppPreferencesImpl.instance.counter; // triggers the guard

      expect(capturedKey, 'counter');
      expect(capturedError, isNotNull);
    });
  });

  // Demonstrates constructor injection: no singleton management required.
  group('AppPreferences (constructor injection)', () {
    late AppPreferencesImpl prefs;

    setUp(() async {
      // Clear the platform store so each test starts clean.
      await SharedPreferencesAsyncPlatform.instance?.clear(
        const ClearPreferencesParameters(filter: PreferencesFilters()),
        const SharedPreferencesOptions(),
      );
      final backend = await SharedPreferencesWithCache.create(
        cacheOptions: const SharedPreferencesWithCacheOptions(),
      );
      // Construct directly — no init() call needed, no global state touched.
      prefs = AppPreferencesImpl(backend);
    });

    tearDown(AppPreferencesImpl.resetInstance);

    test('returns default value for counter initially', () {
      expect(prefs.counter, 0);
      expect(prefs.containsCounter(), isFalse);
    });

    test('sets and gets a value correctly', () async {
      await prefs.setCounter(7);
      expect(prefs.counter, 7);
      expect(prefs.containsCounter(), isTrue);
    });

    test('each test constructs its own independent instance', () {
      // Constructing AppPreferences(backend) directly never touches
      // AppPreferences._instance — the singleton and this instance coexist.
      expect(prefs.counter, 0);
    });

    test('instance getter throws StateError before init()', () {
      AppPreferencesImpl.resetInstance();
      expect(() => AppPreferencesImpl.instance, throwsStateError);
    });
  });
}
