/// This test suite validates the runtime behavior of the code generated by the
/// `shared_prefs_typed` package when operating in `async: true` mode.
///
/// It ensures that all generated getters and helpers correctly return Futures
/// and that the underlying asynchronous APIs of `shared_preferences` are
/// used as expected for all supported data types.
library;

// Import the generated code for the asynchronous preferences.
import 'package:basic_example/async_preferences.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:shared_preferences_platform_interface/in_memory_shared_preferences_async.dart';
import 'package:shared_preferences_platform_interface/shared_preferences_async_platform_interface.dart';
import 'package:shared_preferences_platform_interface/types.dart';

void main() {
  /// This `setUpAll` block runs once before any tests in this suite.
  /// It's the ideal place for one-time test environment configuration.
  setUpAll(() {
    // Ensures that the Flutter test framework is initialized.
    TestWidgetsFlutterBinding.ensureInitialized();

    // CRITICAL SETUP FOR `shared_preferences` TESTING:
    // In a test environment, the native platform implementation (which would
    // write to disk) is unavailable. We must replace it with a mock
    // implementation. `InMemorySharedPreferencesAsync` is a pure Dart,
    // in-memory store that is perfect for fast and reliable tests.
    // This single setup works for both sync and async generated code.
    SharedPreferencesAsyncPlatform.instance = InMemorySharedPreferencesAsync.empty();
  });

  group('AsyncPrefs Generated Code Tests', () {
    // A late-initialized variable to hold the singleton instance of our
    // generated asynchronous preferences service.
    late AsyncPreferencesImpl prefs;

    /// This `setUp` block runs before each individual test within this group.
    /// This ensures that each test begins from a clean, isolated state,
    /// preventing state leakage between tests.
    setUp(() async {
      // 1. Get the singleton instance of our in-memory store.
      final store = SharedPreferencesAsyncPlatform.instance;

      // 2. Clear all data from the store.
      await store?.clear(
        const ClearPreferencesParameters(filter: PreferencesFilters()),
        const SharedPreferencesOptions(),
      );

      // 3. Initialize our generated `AsyncPrefs` service. It will automatically
      //    use the `InMemorySharedPreferencesAsync` instance configured above.
      await AsyncPreferencesImpl.init();
      prefs = AsyncPreferencesImpl.instance;
    });

    group('for async int (pingCount)', () {
      test('returns default value initially', () async {
        // ACT & ASSERT: Getters now return a Future and must be awaited.
        expect(await prefs.pingCount, 0);
        // The `contains` helper also returns a Future.
        expect(await prefs.containsPingCount(), isFalse);
      });

      test('sets and gets a value correctly', () async {
        // ARRANGE
        await prefs.setPingCount(123);

        // ACT & ASSERT
        expect(await prefs.pingCount, 123);
        expect(await prefs.containsPingCount(), isTrue);
      });

      test('removes a value, reverting to default', () async {
        // ARRANGE
        await prefs.setPingCount(123);
        expect(await prefs.pingCount, 123, reason: 'Value should be set before removal');

        // ACT
        await prefs.removePingCount();

        // ASSERT
        expect(await prefs.pingCount, 0, reason: 'Value should revert to default');
        expect(await prefs.containsPingCount(), isFalse, reason: 'Key should no longer be set');
      });
    });

    group('for async nullable String (serverId)', () {
      test('returns default value (null) initially', () async {
        // ACT & ASSERT
        expect(await prefs.serverId, isNull);
        expect(await prefs.containsServerId(), isFalse);
      });

      test('sets and gets a value correctly', () async {
        // ARRANGE
        await prefs.setServerId('server-alpha-x1');

        // ACT & ASSERT
        expect(await prefs.serverId, 'server-alpha-x1');
        expect(await prefs.containsServerId(), isTrue);
      });

      test('setting to null removes the value, reverting to default', () async {
        // ARRANGE
        await prefs.setServerId('server-alpha-x1');
        expect(
          await prefs.containsServerId(),
          isTrue,
          reason: 'Value should be set before setting to null',
        );

        // ACT: Setting a nullable preference to `null` is the same as removing it.
        await prefs.setServerId(null);

        // ASSERT
        expect(await prefs.serverId, isNull);
        expect(await prefs.containsServerId(), isFalse);
      });
    });

    group('for async bool (isCacheEnabled)', () {
      test('returns default value initially', () async {
        // ACT & ASSERT
        expect(await prefs.isCacheEnabled, isTrue);
        expect(await prefs.containsIsCacheEnabled(), isFalse);
      });

      test('sets and gets a value correctly', () async {
        // ARRANGE
        await prefs.setIsCacheEnabled(false);

        // ACT & ASSERT
        expect(await prefs.isCacheEnabled, isFalse);
        expect(await prefs.containsIsCacheEnabled(), isTrue);
      });

      test('removes a value, reverting to default', () async {
        // ARRANGE
        await prefs.setIsCacheEnabled(false);
        expect(await prefs.isCacheEnabled, isFalse, reason: 'Value should be set before removal');

        // ACT
        await prefs.removeIsCacheEnabled();

        // ASSERT
        expect(await prefs.isCacheEnabled, isTrue, reason: 'Value should revert to default');
        expect(
          await prefs.containsIsCacheEnabled(),
          isFalse,
          reason: 'Key should no longer be set',
        );
      });
    });
  });
}
