/// This integration test suite validates the runtime behavior of the code
/// generated by the `shared_prefs_typed` package.
///
/// It ensures that the generated `AppPreferences` service class correctly interacts
/// with the underlying `shared_preferences` plugin's modern asynchronous APIs
/// for all supported data types and scenarios (getting, setting, removing, etc.).
library;

import 'package:flutter_test/flutter_test.dart';
import 'package:shared_preferences_platform_interface/in_memory_shared_preferences_async.dart';
import 'package:shared_preferences_platform_interface/shared_preferences_async_platform_interface.dart';
import 'package:shared_preferences_platform_interface/types.dart';
// Import the generated code.
import 'package:shared_prefs_typed_testing/app_preferences.g.dart';

void main() {
  /// This `setUpAll` block runs once before any tests in this suite.
  /// It's the ideal place for one-time setup.
  setUpAll(() {
    // Ensures that the Flutter test framework is initialized.
    TestWidgetsFlutterBinding.ensureInitialized();

    // CRITICAL SETUP FOR MODERN `shared_preferences` (v2.3.0+):
    // In a test environment, the native platform implementation (like Android's
    // DataStore or iOS's NSUserDefaults) is not available. We must manually
    // provide a "platform implementation".
    // `InMemorySharedPreferencesAsync` is a pure Dart, in-memory store
    // provided by the `shared_preferences_platform_interface` package,
    // which is perfect for fast and reliable tests.
    SharedPreferencesAsyncPlatform.instance = InMemorySharedPreferencesAsync.empty();
  });

  group('AppPreferences Generated Code Tests', () {
    // A late-initialized variable to hold the singleton instance of our
    // generated preferences service.
    late AppPreferences prefs;

    /// This `setUp` block runs before each individual test within this group.
    /// This is used to ensure that each test starts from a clean, isolated state.
    setUp(() async {
      // 1. Get the singleton instance of our in-memory store.
      final store = SharedPreferencesAsyncPlatform.instance;

      // 2. Clear all data from the in-memory store to prevent state leakage
      //    between tests.
      await store?.clear(
        const ClearPreferencesParameters(filter: PreferencesFilters()),
        const SharedPreferencesOptions(),
      );

      // 3. Initialize our generated `AppPrAppPreferencesefs` service. It will automatically
      //    use the `InMemorySharedPreferencesAsync` instance we set up in `setUpAll`.
      await AppPreferences.init();
      prefs = AppPreferences.instance;
    });

    group('for int (counter)', () {
      test('returns default value initially', () {
        expect(prefs.counter, 0);
        expect(prefs.isSetCounter(), isFalse);
      });

      test('sets and gets a value correctly', () async {
        await prefs.setCounter(42);
        expect(prefs.counter, 42);
        expect(prefs.isSetCounter(), isTrue);
      });

      test('removes a value, reverting to default', () async {
        await prefs.setCounter(42);
        expect(prefs.counter, 42); // Verify it was set.

        await prefs.removeCounter();
        expect(prefs.counter, 0); // Should be back to default.
        expect(prefs.isSetCounter(), isFalse);
      });
    });

    group('for double (pi)', () {
      test('returns default value initially', () {
        expect(prefs.pi, 3.14);
        expect(prefs.isSetPi(), isFalse);
      });

      test('sets and gets a value correctly', () async {
        await prefs.setPi(2.718);
        expect(prefs.pi, 2.718);
        expect(prefs.isSetPi(), isTrue);
      });

      test('removes a value, reverting to default', () async {
        await prefs.setPi(2.718);
        await prefs.removePi();
        expect(prefs.pi, 3.14);
        expect(prefs.isSetPi(), isFalse);
      });
    });

    group('for bool (isWelcomeScreenDone)', () {
      test('returns default value initially', () {
        expect(prefs.isWelcomeScreenDone, isFalse);
        expect(prefs.isSetIsWelcomeScreenDone(), isFalse);
      });

      test('sets and gets a value correctly', () async {
        await prefs.setIsWelcomeScreenDone(true);
        expect(prefs.isWelcomeScreenDone, isTrue);
        expect(prefs.isSetIsWelcomeScreenDone(), isTrue);
      });

      test('removes a value, reverting to default', () async {
        await prefs.setIsWelcomeScreenDone(true);
        await prefs.removeIsWelcomeScreenDone();
        expect(prefs.isWelcomeScreenDone, isFalse);
        expect(prefs.isSetIsWelcomeScreenDone(), isFalse);
      });
    });

    group('for String (greeting)', () {
      test('returns default value initially', () {
        expect(prefs.greeting, 'Hello');
        expect(prefs.isSetGreeting(), isFalse);
      });

      test('sets and gets a value correctly', () async {
        await prefs.setGreeting('World');
        expect(prefs.greeting, 'World');
        expect(prefs.isSetGreeting(), isTrue);
      });

      test('removes a value, reverting to default', () async {
        await prefs.setGreeting('World');
        await prefs.removeGreeting();
        expect(prefs.greeting, 'Hello');
        expect(prefs.isSetGreeting(), isFalse);
      });
    });

    group('for List<String> (tagList)', () {
      test('returns default value initially', () {
        expect(prefs.tagList, ['default']);
        expect(prefs.isSetTagList(), isFalse);
      });

      test('sets and gets a value correctly', () async {
        await prefs.setTagList(['flutter', 'dart']);
        expect(prefs.tagList, ['flutter', 'dart']);
        expect(prefs.isSetTagList(), isTrue);
      });

      test('removes a value, reverting to default', () async {
        await prefs.setTagList(['flutter', 'dart']);
        await prefs.removeTagList();
        expect(prefs.tagList, ['default']);
        expect(prefs.isSetTagList(), isFalse);
      });
    });

    group('for nullable String (sessionId)', () {
      test('returns default value (null) initially', () {
        expect(prefs.sessionId, isNull);
        expect(prefs.isSetSessionId(), isFalse);
      });

      test('sets and gets a value correctly', () async {
        await prefs.setSessionId('abc-123');
        expect(prefs.sessionId, 'abc-123');
        expect(prefs.isSetSessionId(), isTrue);
      });

      test('setting to null removes the value', () async {
        await prefs.setSessionId('abc-123');
        expect(prefs.isSetSessionId(), isTrue); // Verify it was set.

        await prefs.setSessionId(null); // Set to null.
        expect(prefs.sessionId, isNull); // Should be back to default (null).
        expect(prefs.isSetSessionId(), isFalse);
      });
    });

    group('for nullable int with non-null default (nullableCounterWithDefault)', () {
      test('returns default value (100) initially', () {
        expect(prefs.nullableCounterWithDefault, 100);
        expect(prefs.isSetNullableCounterWithDefault(), isFalse);
      });

      test('sets and gets a value correctly', () async {
        await prefs.setNullableCounterWithDefault(999);
        expect(prefs.nullableCounterWithDefault, 999);
        expect(prefs.isSetNullableCounterWithDefault(), isTrue);
      });

      test('setting to null removes the value, reverting to default', () async {
        await prefs.setNullableCounterWithDefault(999);
        expect(prefs.isSetNullableCounterWithDefault(), isTrue);

        await prefs.setNullableCounterWithDefault(null);
        expect(prefs.nullableCounterWithDefault, 100); // Should be back to default.
        expect(prefs.isSetNullableCounterWithDefault(), isFalse);
      });

      test('explicit remove reverts to default', () async {
        await prefs.setNullableCounterWithDefault(999);
        await prefs.removeNullableCounterWithDefault();
        expect(prefs.nullableCounterWithDefault, 100);
        expect(prefs.isSetNullableCounterWithDefault(), isFalse);
      });
    });
  });
}
